version: '3.8'

services:
    php:
        build: docker/php
        volumes:
            - .:/var/www/html
        environment:
            XDEBUG_MODE: debug
            XDEBUG_CONFIG: "client_host=host.docker.internal"
        extra_hosts:
            - "host.docker.internal:host-gateway"

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        depends_on:
            - php

    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: symfony_db
            POSTGRES_USER: symfony_user
            POSTGRES_PASSWORD: secret
        ports:
            - "5433:5432"
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data:
